version: '3.8'

services:

  db:
    image: postgres:15
    container_name: vault-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: StrongPass123
      POSTGRES_DB: vaultwarden
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vault-net

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgresql://vault:StrongPass123@db:5432/vaultwarden
      ADMIN_TOKEN: AdminSecretToken
      SIGNUPS_ALLOWED: "true"
    depends_on:
      - db
    networks:
      - vault-net

volumes:
  db_data:

networks:
  vault-net:
    driver: bridge
